################################################################################
# Docker compose Drupal full dev stack.
#
# A single Docker compose file that try to simply and quickly setup a full
# Drupal development environment.
#
# Project page:
#   https://github.com/Mogtofu33/docker-compose-drupal
#
# Quick set-up:
#  Copy this file, rename to docker-compose.yml, comment or remove services
#  definition based on your needs.
#  Copy and rename default.env to .env
#  Launch:
#    docker-compose up
#
# You can check your config after editing this file with:
#   docker-compose config
#
# Services settings are in config folder, check and adapt to your needs.
#
# For more information on docker compose file structure:
# @see https://docs.docker.com/compose/
#
################################################################################
version: '3'
volumes:
  sock:
services:
  apache:
    image: mogtofu33/apache
    ports:
      - "${APACHE_HOST_HTTP_PORT:-80}:80"
      - "${APACHE_HOST_HTTPS_PORT:-443}:443"
      # Web root access, optionnal.
      - 81:81
      # Used by dashboard.
      - "${APACHE_HOST_DASHBORAD_PORT:-8181}:8181"
    links:
      - php
    volumes:
      - ${HOST_WEB_ROOT:-./data/www}:/var/www/localhost
      # Apache configuration with SSL support.
      - ./config/apache/httpd.conf:/etc/apache2/httpd.conf
      - ./config/apache/vhost.conf:/etc/apache2/vhost.conf
      - ./config/apache/conf.d/:/etc/apache2/conf.d/
      - ./config/apache/ssl/:/etc/ssl/apache2/
      # Used by dashboard and tools.
      - ./build/dashboard/build:/var/www/dashboard
      - ./tools:/var/www/dashboard/tools
      # Php FPM socket
      - sock:/sock
    env_file: .env
    container_name: dcd-apache
    ## Remove to avoid starting on system reboot.
    restart: always
  php:
    image: mogtofu33/php
    volumes:
      - ${HOST_WEB_ROOT:-./data/www}:/var/www/localhost
      - ./config/php/php.ini:/etc/php7/php.ini
      - ./config/php/php-fpm.conf:/etc/php7/php-fpm.conf
      - ./config/php/conf.d/:/etc/php7/conf.d/
      - ./config/php/php-fpm.d/:/etc/php7/php-fpm.d/
      # Drush alias and drushrc files (or any other config)
      - ./config/drush/aliases.drushrc.php:/etc/drush/aliases.drushrc.php
      - ./config/drush/drushrc.php:/etc/drush/drushrc.php
      # Drush 9 alias and drushrc files (or any other config)
      - ./config/drush/d.alias.yml:/etc/drush/d.alias.yml
      - ./config/drush/drush.yml:/etc/drush/drush.yml
      # Used by dashboard and tools.
      - ./build/dashboard/build:/var/www/dashboard
      - ./tools:/var/www/dashboard/tools
      - /var/run/docker.sock:/var/run/docker.sock
      # Php FPM socket
      - sock:/sock
      ## If you have composer set locally, share cache to speed up.
      # - $HOME/.composer/cache:/composer/cache
    links:
      # Choose database, uncomment service concerned below.
      - mysql
      - pgsql
      # Choose optionnal services.
      - memcache
      - redis
      - solr
      - mailhog
    env_file: .env
    container_name: dcd-php
    # privileged is needed to access docker.sock
    privileged: true
    # Remove to avoid starting on system reboot.
    restart: always
  mysql:
    image: mariadb:latest
    # image: mysql:latest
    expose:
      - "3306"
    volumes:
      ## Comment these two lines on Windows system, permissions issue.
      - ${HOST_DATABASE_MYSQL:-./data/database/mysql}:/var/lib/mysql
      - ./config/mysql:/etc/mysql
    env_file: .env
    ## Remove to avoid starting on system reboot.
    restart: always
  pgsql:
    image: postgres:alpine
    expose:
      - "5432"
    ## Comment these two lines on Windows system, permissions issue.
    volumes:
      - ${HOST_DATABASE_POSTGRES:-./data/database/pgsql}:/var/lib/postgresql/data
    env_file: .env
    ## Remove to avoid starting on system reboot.
    restart: always
  # varnish:
  #   build: ./build/varnish
  #   ports:
  #     - "${VARNISH_HOST_PORT:-8080}:80"
  #     - "6082:6082"
  #   links:
  #     - apache
  #   env_file: .env
  #   ## Remove to avoid starting on system reboot.
  #   restart: always
  # ldap:
  #   image: osixia/openldap:latest
  #   ports:
  #     - "389:389"
  #   ## Remove to avoid starting on system reboot.
  #   restart: always
  # ldapadmin:
  #   image: osixia/phpldapadmin:latest
  #   links:
  #     - ldap
  #   ports:
  #     - "8443:8443"
  #   ## Remove to avoid starting on system reboot.
  #   restart: always
